# Generated by Django 5.1.15 on 2026-07-21 07:45

import apps.core.domains
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_branch_is_active_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(choices=apps.core.domains.domain_choices, default='general', max_length=32, verbose_name='industry'),
        ),
    ]
