# Generated by Django 5.1.15 on 2026-07-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_rls_empty_guc_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='BHD', max_length=8, verbose_name='currency'),
        ),
    ]
