# Generated by Django 5.1.15 on 2026-07-22 06:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_tenant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cr_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='CR number'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='default tax rate %'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='legal name'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='VAT registration no.'),
        ),
    ]
