# Generated by Django 5.1.15 on 2026-07-21 08:34

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0003_rls_empty_guc_guard'),
        ('tenancy', '0006_tenant_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('default_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='default amount')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='taxable')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant', verbose_name='tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'charge type',
                'verbose_name_plural': 'charge types',
                'ordering': ['sort_order', 'name'],
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30, verbose_name='reference')),
                ('worker_name', models.CharField(blank=True, max_length=200, verbose_name='worker name')),
                ('occupation_name', models.CharField(blank=True, max_length=100, verbose_name='occupation')),
                ('route', models.CharField(choices=[('transfer', 'Visa transfer (in country)'), ('overseas', 'Overseas recruitment')], max_length=20, verbose_name='route')),
                ('visa_period_months', models.PositiveSmallIntegerField(choices=[(12, '1 year'), (24, '2 years')], default=24, verbose_name='visa period')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('agreed_on', models.DateField(blank=True, null=True, verbose_name='agreed on')),
                ('medical_on', models.DateField(blank=True, null=True, verbose_name='medical completed')),
                ('visa_applied_on', models.DateField(blank=True, null=True, verbose_name='visa applied')),
                ('visa_issued_on', models.DateField(blank=True, null=True, verbose_name='visa issued')),
                ('travel_on', models.DateField(blank=True, null=True, verbose_name='travel date')),
                ('arrival_on', models.DateField(blank=True, null=True, verbose_name='arrival date')),
                ('delivered_on', models.DateField(blank=True, null=True, verbose_name='delivered on')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='contract start')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='contract end')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='invoice date')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Applied to taxable lines only.', max_digits=5, verbose_name='tax rate %')),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='discount')),
                ('amount_paid', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='amount paid')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='payment terms')),
                ('terms', models.TextField(blank=True, verbose_name='terms and conditions')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='manpower.sponsor', verbose_name='sponsor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant', verbose_name='tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='manpower.worker', verbose_name='worker')),
            ],
            options={
                'verbose_name': 'placement',
                'verbose_name_plural': 'placements',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlacementCharge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='amount')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='taxable')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='manpower.placement', verbose_name='placement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant', verbose_name='tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charges',
                'ordering': ['sort_order', 'id'],
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['tenant', 'status'], name='manpower_pl_tenant__650209_idx'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference'), name='uniq_placement_tenant_reference'),
        ),
    ]
