# Generated by Django 5.1.15 on 2026-07-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0005_rls_placements'),
        # Must run AFTER the charges have been copied into billing invoices —
        # this migration drops the columns they live in.
        ('billing', '0003_move_placement_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementcharge',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='placementcharge',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='placementcharge',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='placementcharge',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='tax_rate',
        ),
        migrations.DeleteModel(
            name='ChargeType',
        ),
        migrations.DeleteModel(
            name='PlacementCharge',
        ),
    ]
