# Generated by Django 5.1.15 on 2026-07-22 06:10

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0006_remove_placementcharge_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.FileField(blank=True, upload_to=apps.core.models.tenant_upload_to('workers'), verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='workerdocument',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.core.models.tenant_upload_to('worker-documents'), verbose_name='file'),
        ),
    ]
